services:
  caddy:
    container_name: ft_transcendence_caddy
    image: caddy:2.11.2-alpine
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_HOST_PORT:-7080}:80"
      - "${CADDY_HTTPS_HOST_PORT:-7443}:443"
    environment:
      HTTP_DOMAINS: ${CADDY_HTTP_DOMAINS}
      HTTPS_DOMAINS: ${CADDY_HTTPS_DOMAINS}
      FRONTEND_PORT: ${FRONTEND_INTERNAL_PORT}
      BACKEND_PORT: ${BACKEND_INTERNAL_PORT}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/scalar.html:/srv/index.html
      - caddy_data:/data

  frontend:
    container_name: ft_transcendence_frontend
    build: ./frontend
    restart: unless-stopped
    environment:
      PORT: ${FRONTEND_INTERNAL_PORT}
      NODE_ENV: ${NODE_ENV}

  backend:
    container_name: ft_transcendence_backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: ${BACKEND_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_INTERNAL_PORT}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      CONTAINER_RUNTIME: true

  prometheus:
    container_name: ft_transcendence_prometheus
    image: prom/prometheus:v3.12.0
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${PROMETHEUS_HOST_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    container_name: ft_transcendence_grafana
    image: grafana/grafana:13.0.2
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_HOST_PORT:-3001}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana

  postgres:
    container_name: ft_transcendence_postgres
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  caddy_data:
  prometheus_data:
  grafana_data:
