services:
  frontend:
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_INTERNAL_PORT}"

  backend:
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_INTERNAL_PORT}"

  postgres:
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_INTERNAL_PORT}"

  prometheus:
    ports:
      - "${PROMETHEUS_HOST_PORT:-9090}:9090"
