services:
  caddy:
    container_name: ft_transcendence_caddy
    image: caddy:2.11.2-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-7080}:80"
      - "${HTTPS_PORT:-7443}:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/scalar.html:/srv/index.html
      - caddy_data:/data

  frontend:
    container_name: ft_transcendence_frontend
    build: ./frontend
    restart: unless-stopped

  backend:
    container_name: ft_transcendence_backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CONTAINER_RUNTIME: "true"

  postgres:
    container_name: ft_transcendence_postgres
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  caddy_data:
