services:
  caddy:
    container_name: ft_transcendence_caddy
    image: caddy:2.11.2-alpine
    restart: unless-stopped
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - $PWD:/etc/caddy
      - caddy_data:/data

  frontend:
    container_name: ft_transcendence_frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "7779:7771"

  backend:
    container_name: ft_transcendence_backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: ft_transcendence_postgres
    image: postgres:18.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: ft_transcendence
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  caddy_data:
